version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  hold:
    type: approval
  build-and-test:
    requires:
      - hold
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - hold
        - build-and-test
